---
title: "Install packages"
author: "Erich Neuwirth"
date: "4 May 2016"
output: html_document
---

```{r setup, include=FALSE}
# installed with R
inst <- c("base", "boot", "class", "cluster", "codetools", "compiler", 
"datasets", "foreign", "graphics", "grDevices", "grid", "KernSmooth", 
"lattice", "MASS", "Matrix", "methods", "mgcv", "nlme", "nnet", 
"parallel", "rpart", "spatial", "splines", "stats", "stats4", 
"survival", "tcltk", "tools", "utils")

# installed with rstudio

instrstudio <-
c("base", "bitops", "boot", "caTools", "class", "cluster", "codetools", 
"compiler", "datasets", "digest", "evaluate", "foreign", "formatR", 
"graphics", "grDevices", "grid", "highr", "htmltools", "KernSmooth", 
"knitr", "lattice", "magrittr", "markdown", "MASS", "Matrix", 
"methods", "mgcv", "mime", "nlme", "nnet", "parallel", "Rcpp", 
"rmarkdown", "rpart", "spatial", "splines", "stats", "stats4", 
"stringi", "stringr", "survival", "tcltk", "tools", "utils", 
"yaml")

# Max

max <- c("abc", "abc.data", "abind", "acepack", "actuar", "ada", "adabag", 
"ade4", "ade4TkGUI", "adegraphics", "ADGofTest", "AER", "AGD", 
"agricolae", "AICcmodavg", "akima", "AlgDesign", "AllPossibleSpellings", 
"alr3", "alr4", "amap", "Amelia", "anchors", "anesrake", "animation", 
"aod", "ape", "aplpack", "arm", "arules", "arulesViz", "ascii", 
"ash", "assertthat", "audio", "barcode", "base", "base64", "base64enc", 
"bayesm", "BayesX", "BB", "bbmle", "BCA", "BDgraph", "bdsmatrix", 
"BH", "BHH2", "BiasedUrn", "bibtex", "biclust", "biglm", "bit", 
"bit64", "bitops", "BMA", "boilerpipeR", "boot", "Boruta", "BradleyTerry2", 
"brew", "brglm", "broom", "BsMD", "bst", "C50", "ca", "Cairo", 
"calibrator", "candisc", "car", "caret", "catdata", "caTools", 
"cba", "ccaPP", "cec2005benchmark", "cec2013", "cem", "checkpoint", 
"chron", "CircStats", "circular", "class", "classInt", "clinfun", 
"clue", "cluster", "clv", "cmprsk", "cobs", "coda", "codetools", 
"coin", "colorRamps", "colorspace", "combinat", "compiler", "compositions", 
"CompQuadForm", "compute.es", "conf.design", "contfrac", "contrast", 
"copula", "copulaedas", "corpcor", "corrgram", "corrplot", "cowplot", 
"coxme", "cranvas", "crayon", "crp.CSFP", "ctv", "cubature", 
"Cubist", "cumplyr", "curl", "cvTools", "d3Network", "DAAG", 
"data.table", "dataframes2xls", "datasets", "date", "dbConnect", 
"DBI", "Deducer", "DeducerExtras", "DeducerPlugInExample", "degreenet", 
"deldir", "demography", "dendextend", "densityvis", "denstrip", 
"DEoptimR", "depthTools", "descr", "DescTools", "deSolve", "devtools", 
"dfoptim", "diagram", "DiagrammeR", "DiceDesign", "dichromat", 
"digest", "diptest", "distr", "distrEx", "DistributionUtils", 
"distrMod", "distrSim", "distrTeach", "distrTEst", "doBy", "DoE.base", 
"DoE.wrapper", "doMC", "doParallel", "doRedis", "DoseFinding", 
"doSNOW", "downloader", "dplyr", "DSL", "dtw", "dull", "dygraphs", 
"dynlm", "e1071", "earth", "Ecdat", "Ecfun", "ecodist", "EcoVirtual", 
"effects", "elasticnet", "ElemStatLearn", "ellipse", "elliptic", 
"emdbook", "emulator", "energy", "ENmisc", "EnQuireR", "entropy", 
"Epi", "epiR", "epitools", "eRm", "etm", "evaluate", "evd", "evtree", 
"exactRankTests", "expm", "expsmooth", "extrafont", "extrafontdb", 
"ez", "FactoMineR", "Fahrmeir", "fArma", "fAsianOptions", "fAssets", 
"fastICA", "fastmatch", "fBasics", "fCopulae", "fda", "fdrtool", 
"fds", "feather", "fExoticOptions", "fExtremes", "fGarch", "fields", 
"filehash", "fImport", "FinTS", "fit.models", "flashClust", "flexclust", 
"flexmix", "flsa", "Flury", "fma", "FME", "FMStable", "fMultivar", 
"FNN", "fNonlinear", "foba", "fontcm", "fOptions", "foreach", 
"forecast", "foreign", "formatR", "Formula", "fortunes", "fpc", 
"fpp", "fracdiff", "FRB", "fRegression", "FrF2", "FrF2.catlg128", 
"fTrading", "fts", "ftsa", "FuncMap", "functools", "fUnitRoots", 
"gam", "gamlss", "gamlss.data", "gamlss.dist", "gamm4", "gapminder", 
"gbm", "gclus", "gdata", "gee", "geepack", "GeneralizedHyperbolic", 
"geoR", "geoRglm", "geosphere", "getopt", "GGally", "ggalt", 
"ggdendro", "gglasso", "ggm", "ggmap", "ggmcmc", "ggparallel", 
"ggplot2", "ggROC", "ggsubplot", "ggtern", "ggthemes", "ggvis", 
"git2r", "glasso", "glmmLasso", "glmnet", "gmodels", "gmp", "gnm", 
"gnumeric", "gof", "goftest", "googleVis", "gpairs", "GPArotation", 
"gpclib", "gplots", "granova", "graphics", "gRc", "grDevices", 
"grid", "gridBase", "gridExtra", "gridSVG", "grImport", "gsl", 
"gss", "gstat", "gsubfn", "gtable", "gtools", "gWidgets", "gWidgets2", 
"gWidgets2RGtk2", "gWidgets2tcltk", "gWidgetstcltk", "HadoopStreaming", 
"haven", "hda", "HDclassif", "hdi", "hdrcde", "heatmap.plus", 
"heplots", "hexbin", "hflights", "HH", "highlight", "highr", 
"HistData", "histogram", "hive", "hmeasure", "Hmisc", "HSAUR", 
"htmltools", "HTMLUtils", "htmlwidgets", "httpRequest", "httpuv", 
"httr", "huge", "hwriter", "hwriterPlus", "hypergeo", "igraph", 
"igraphdata", "ineq", "inline", "inlinedocs", "intergraph", "intervals", 
"iplots", "ipred", "IPSUR", "irlba", "irr", "isa2", "ISOcodes", 
"ISwR", "iterators", "itertools", "its", "JavaGD", "JGR", "jpeg", 
"jsonlite", "Kendall", "kernlab", "KernSmooth", "kinship2", "kknn", 
"klaR", "kml", "knitcitations", "knitr", "kohonen", "koRpus", 
"KRLS", "ks", "labeling", "Lahman", "languageR", "lars", "lasso2", 
"latex2exp", "lattice", "latticeExtra", "lava", "lavaan", "lavaan.survey", 
"lawstat", "lazyeval", "leaflet", "leafletR", "leaps", "LearnBayes", 
"lfstat", "lhs", "linprog", "lisrelToR", "lme4", "lmerTest", 
"lmom", "lmomRFA", "lmtest", "loa", "locfit", "logcondens", "LogicForest", 
"LogicReg", "logspline", "lokern", "longitudinalData", "longmemo", 
"lpSolve", "lpSolveAPI", "lubridate", "MAc", "MAd", "magic", 
"magrittr", "mailR", "manipulate", "mapdata", "mapproj", "maps", 
"maptools", "markdown", "MASS", "Matching", "MatchIt", "mathgraph", 
"matlab", "Matrix", "matrixcalc", "MatrixModels", "maxLik", "MBESS", 
"mboost", "mclust", "mcmc", "MCMCpack", "mda", "memoise", "MEMSS", 
"meta", "metafor", "metatest", "methods", "mets", "mFilter", 
"mgcv", "mi", "mice", "microbenchmark", "mime", "miniUI", "minpack.lm", 
"minqa", "misc3d", "miscTools", "missMDA", "mitools", "mix", 
"mixlm", "mixRasch", "mlbench", "mlmRev", "mlogit", "mnormt", 
"modeltools", "moments", "mondate", "MPV", "mratios", "mstate", 
"multcomp", "multicool", "multilevel", "MuMIn", "munsell", "mvbutils", 
"mvnormtest", "mvoutlier", "mvtnorm", "ncdf", "ncdf4", "ndtv", 
"neldermead", "network", "networkDynamic", "networksis", "neuralnet", 
"nlme", "nloptr", "NLP", "NMF", "nnet", "nnls", "nodeHarvest", 
"nor1mix", "nortest", "np", "numDeriv", "nws", "nycflights13", 
"objectProperties", "objectSignals", "obliqueRF", "odfWeave", 
"odfWeave.survey", "openair", "OpenMx", "openssl", "optextras", 
"optimbase", "optimsimplex", "optimx", "optmatch", "optparse", 
"ordinal", "orloca", "orloca.es", "oz", "pamr", "pan", "pander", 
"parallel", "partDSA", "partitions", "party", "partykit", "pastecs", 
"pbapply", "pbivnorm", "pbkrtest", "PBSmapping", "PBSmodelling", 
"pcaPP", "penalized", "penalizedLDA", "pequod", "PerformanceAnalytics", 
"permute", "pipeR", "pitchRx", "pixmap", "pkgKitten", "pkgmaker", 
"PKPDmodels", "plm", "plotly", "plotmo", "plotrix", "plRasch", 
"pls", "plumbr", "plyr", "pmml", "pmmlTransformations", "png", 
"poistweedie", "poLCA", "polspline", "polyclip", "polycor", "polynom", 
"PolynomF", "pps", "prabclus", "pracma", "praise", "PredictABEL", 
"prefmod", "prettyR", "prettyunits", "prim", "princurve", "prob", 
"pROC", "prodlim", "productplots", "profileModel", "progress", 
"proj4", "proto", "proxy", "pryr", "pscl", "pspline", "psych", 
"psychotools", "psychotree", "purrr", "pwr", "qap", "qcc", "qgraph", 
"qrnn", "qtbase", "QTLRel", "qtpaint", "quadprog", "quantmod", 
"quantreg", "quantregForest", "questionr", "qvcalc", "R.cache", 
"R.devices", "R.huge", "R.matlab", "R.methodsS3", "R.oo", "R.rsp", 
"R.utils", "R2HTML", "R2jags", "R2SWF", "R2WinBUGS", "R6", "rainbow", 
"RandomFields", "RandomFieldsUtils", "randomForest", "randomForestSRC", 
"randtests", "randtoolbox", "RandVar", "ranger", "RANN", "rappdirs", 
"RArcInfo", "RaschSampler", "raster", "rasterVis", "rattle", 
"rbenchmark", "Rcgmin", "Rcmdr", "RcmdrMisc", "RcmdrPlugin.BCA", 
"RcmdrPlugin.coin", "RcmdrPlugin.depthTools", "RcmdrPlugin.DoE", 
"RcmdrPlugin.doex", "RcmdrPlugin.EACSPIR", "RcmdrPlugin.EBM", 
"RcmdrPlugin.EcoVirtual", "RcmdrPlugin.epack", "RcmdrPlugin.EZR", 
"RcmdrPlugin.FactoMineR", "RcmdrPlugin.HH", "RcmdrPlugin.IPSUR", 
"RcmdrPlugin.KMggplot2", "RcmdrPlugin.lfstat", "RcmdrPlugin.MA", 
"RcmdrPlugin.mosaic", "RcmdrPlugin.MPAStats", "RcmdrPlugin.NMBU", 
"RcmdrPlugin.orloca", "RcmdrPlugin.plotByGroup", "RcmdrPlugin.pointG", 
"RcmdrPlugin.qual", "RcmdrPlugin.ROC", "RcmdrPlugin.sampling", 
"RcmdrPlugin.SCDA", "RcmdrPlugin.seeg", "RcmdrPlugin.SLC", "RcmdrPlugin.SM", 
"RcmdrPlugin.sos", "RcmdrPlugin.StatisticalURV", "RcmdrPlugin.steepness", 
"RcmdrPlugin.survival", "RcmdrPlugin.TeachingDemos", "RcmdrPlugin.temis", 
"RcmdrPlugin.UCA", "RColorBrewer", "Rcpp", "RcppArmadillo", "RcppEigen", 
"Rcsdp", "RCurl", "Rd2roxygen", "readr", "readxl", "ref", "RefManageR", 
"registry", "regtest", "relations", "relax", "relaxo", "relevent", 
"relimp", "reshape", "reshape2", "ResourceSelection", "rFerns", 
"rgdal", "rgenoud", "rgeos", "rgl", "RgoogleMaps", "RGraphics", 
"RGtk2", "RInside", "rite", "RItools", "rjags", "rJava", "rjson", 
"RJSONIO", "rJython", "rleafmap", "rlecuyer", "rmarkdown", "rmdformats", 
"rmeta", "rminer", "Rmpfr", "rms", "RMySQL", "RNetLogo", "rngtools", 
"rngWELL", "ROAuth", "robCompositions", "robust", "robustbase", 
"rocc", "rockchalk", "ROCR", "RODBC", "Rook", "rootSolve", "roxygen2", 
"rpanel", "rpart", "rpart.plot", "rpf", "rPython", "rrcov", "rredis", 
"RRF", "rrlda", "RSclient", "rscproxy", "Rserve", "rsm", "RSNNS", 
"Rsolnp", "RSQLite", "rstudio", "rstudioapi", "RSvgDevice", "RSVGTipsDevice", 
"rSymPy", "rticles", "rtiff", "Rttf2pt1", "rugarch", "RUnit", 
"rversions", "rvest", "Rvmmin", "RWeka", "RWekajars", "Ryacas", 
"sampleSelection", "SampleSizeMeans", "SampleSizeProportions", 
"sampling", "samplingbook", "sandwich", "scagnostics", "scales", 
"scalreg", "scatterplot3d", "SciViews", "SCMA", "SCRT", "SCVA", 
"sda", "sde", "SearchTrees", "seeg", "segmented", "selectr", 
"sem", "semPlot", "semTools", "sendmailR", "sendplot", "SensoMineR", 
"seriation", "setRNG", "sets", "sfsmisc", "sgeostat", "shape", 
"shapefiles", "shapes", "shiny", "shinyTree", "showtext", "showtextdb", 
"signal", "SimComp", "simecol", "SimpleTable", "simsem", "SixSigma", 
"sjdbc", "sjmisc", "sjPlot", "SkewHyperbolic", "slam", "SLC", 
"Sleuth2", "sm", "sn", "sna", "snow", "SnowballC", "snowfall", 
"snowFT", "soiltexture", "som", "sos", "sp", "spacetime", "spam", 
"sparseLDA", "SparseM", "spatial", "spatialkernel", "spatstat", 
"spc", "spd", "spdep", "splancs", "splines", "spls", "sROC", 
"stabledist", "stabs", "StanHeaders", "startupmsg", "stashR", 
"stationaRy", "statmod", "statnet.common", "stats", "stats4", 
"steepness", "stepPlr", "stringdist", "stringi", "stringr", "strucchange", 
"subselect", "sudoku", "superpc", "survey", "survival", "svd", 
"svDialogs", "svGUI", "svIDE", "svMisc", "svSocket", "svSweave", 
"svTools", "svUnit", "svWidgets", "SweaveListingUtils", "swirl", 
"symbols", "sysfonts", "systemfit", "tableone", "tables", "tagcloud", 
"tcltk", "tcltk2", "tclust", "TeachingDemos", "TeachingSampling", 
"tensor", "tensorA", "testit", "testthat", "tfplot", "tframe", 
"tframePlus", "TH.data", "tidyr", "tikzDevice", "timeDate", "timereg", 
"timeSeries", "tis", "tkrplot", "tm", "tm.plugin.alceste", "tm.plugin.dc", 
"tm.plugin.europresse", "tm.plugin.factiva", "tm.plugin.lexisnexis", 
"tm.plugin.mail", "tm.plugin.webmining", "tnet", "tools", "tourr", 
"tree", "trimcluster", "tripack", "truncnorm", "truncreg", "trust", 
"TSA", "TSdbi", "tsDyn", "tseries", "tseriesChaos", "TSP", "TSxls", 
"TSzip", "TTR", "tufte", "tufterhandout", "tuneR", "tweedie", 
"twitteR", "ucminf", "unmarked", "urca", "UScensus2000cdp", "UScensus2000tract", 
"UsingR", "utils", "V8", "vars", "vcd", "vcdExtra", "Vdgraph", 
"vdmR", "VecStatGraphs2D", "VecStatGraphs3D", "vegan", "venneuler", 
"verification", "VGAM", "VGAMdata", "VIM", "vines", "violinmplot", 
"vioplot", "viridis", "viridisLite", "visNetwork", "vrmlgen", 
"waveslim", "weightedKmeans", "weights", "WhatIf", "whisker", 
"wikibooks", "withr", "wordcloud", "WriteXLS", "xkcd", "XLConnect", 
"XLConnectJars", "xlsx", "xlsxjars", "XML", "xml2", "XML2R", 
"xtable", "xts", "yaImpute", "YaleToolkit", "yaml", "Zelig", 
"zipcode", "zipfR", "zoo")

# Mozart

mozart <- c("abind", "acepack", "ada", "addinexamples", "ade4", "agricolae", 
"AlgDesign", "animation", "animint", "aod", "aplpack", "arm", 
"assertthat", "barcode", "base64enc", "BCA", "BH", "BiasedUrn", 
"BiocGenerics", "BiocInstaller", "bit", "bit64", "bitops", "bookdown", 
"brew", "broom", "BsMD", "ca", "Cairo", "cairoDevice", "car", 
"caTools", "chron", "classInt", "clinfun", "clv", "cmprsk", "coda", 
"coin", "colorspace", "combinat", "compute.es", "conf.design", 
"corpcor", "cowplot", "crantastic", "cranvas", "crayon", "curl", 
"d3Network", "dae", "data.table", "dataframes2xls", "date", "DBI", 
"ddR", "deldir", "densityvis", "depthTools", "devtools", "DiagrammeR", 
"DiceDesign", "dichromat", "digest", "directlabels", "distr", 
"distrEx", "DoE.base", "DoE.wrapper", "doMC", "doParallel", "dostats", 
"dplyr", "dygraphs", "e1071", "EBImage", "EcoVirtual", "effects", 
"ellipse", "emoGG", "emojifont", "ENmisc", "ensurer", "epiR", 
"epitools", "evaluate", "extrafont", "extrafontdb", "ez", "FactoMineR", 
"fdrtool", "feather", "fftw", "fftwtools", "fields", "filehash", 
"flashClust", "flexclust", "foreach", "forecast", "formatR", 
"Formula", "fracdiff", "FrF2", "FrF2.catlg128", "functools", 
"gdata", "gdtools", "gender", "geosphere", "getcartr", "GGally", 
"GGEBiplotGUI", "ggExtra", "ggfreehand", "ggm", "ggmap", "ggplot2", 
"ggthemes", "ggvis", "GISTools", "git2r", "gittest", "glasso", 
"glmnet", "gmodels", "gmp", "goftest", "googleformr", "gpairs", 
"gplots", "graph", "gridBase", "gridExtra", "gridSVG", "gtable", 
"gtools", "gWidgets", "gWidgets2", "gWidgets2RGtk2", "gWidgets2tcltk", 
"gWidgetsRGtk2", "gWidgetstcltk", "harvestr", "haven", "hexbin", 
"HH", "highr", "Hmisc", "htmltools", "htmlwidgets", "httpuv", 
"httr", "huge", "igraph", "inline", "irlba", "ISOcodes", "iterators", 
"jpeg", "jsonlite", "kernlab", "klaR", "knitr", "labeling", "Lahman", 
"latticeExtra", "lavaan", "lazyeval", "leaflet", "leafletR", 
"leaps", "LearnBayes", "lfstat", "lhs", "likert", "lme4", "lmom", 
"lmomRFA", "lmtest", "loa", "locfit", "loon", "lpSolve", "lubridate", 
"MAd", "magrittr", "mailR", "manipulate", "mapproj", "maps", 
"maptools", "markdown", "matrixcalc", "MatrixModels", "mcmc", 
"MCMCpack", "memoise", "meta", "metafor", "metatest", "mi", "microbenchmark", 
"mime", "miniCRAN", "miniUI", "minqa", "mixlm", "mnormt", "modeltools", 
"multcomp", "munsell", "mvtnorm", "nloptr", "NLP", "NMF", "nortest", 
"nycflights13", "objectProperties", "objectSignals", "openssl", 
"openxlsx", "optmatch", "ordinal", "orloca", "orloca.es", "osmar", 
"pack", "PairViz", "pbapply", "pbivnorm", "pbkrtest", "PBSmapping", 
"PBSmodelling", "pipeR", "pixmap", "pkgmaker", "plotly", "pls", 
"plumbr", "plyr", "png", "polyclip", "pracma", "praise", "PredictABEL", 
"prettyR", "pROC", "productplots", "proto", "pryr", "psych", 
"purrr", "PythonInR", "qcc", "qgraph", "qtbase", "qtpaint", "quadprog", 
"quantreg", "questionr", "R.methodsS3", "R.oo", "R.utils", "R2HTML", 
"R6", "randtests", "raster", "rasterVis", "Rcartogram", "rCharts", 
"Rcmdr", "RcmdrMisc", "RcmdrPlugin.BCA", "RcmdrPlugin.coin", 
"RcmdrPlugin.depthTools", "RcmdrPlugin.DoE", "RcmdrPlugin.doex", 
"RcmdrPlugin.EACSPIR", "RcmdrPlugin.EBM", "RcmdrPlugin.EcoVirtual", 
"RcmdrPlugin.epack", "RcmdrPlugin.EZR", "RcmdrPlugin.FactoMineR", 
"RcmdrPlugin.HH", "RcmdrPlugin.IPSUR", "RcmdrPlugin.KMggplot2", 
"RcmdrPlugin.lfstat", "RcmdrPlugin.MA", "RcmdrPlugin.mosaic", 
"RcmdrPlugin.MPAStats", "RcmdrPlugin.NMBU", "RcmdrPlugin.orloca", 
"RcmdrPlugin.plotByGroup", "RcmdrPlugin.pointG", "RcmdrPlugin.qual", 
"RcmdrPlugin.RMTCJags", "RcmdrPlugin.ROC", "RcmdrPlugin.sampling", 
"RcmdrPlugin.SCDA", "RcmdrPlugin.seeg", "RcmdrPlugin.SLC", "RcmdrPlugin.SM", 
"RcmdrPlugin.sos", "RcmdrPlugin.StatisticalURV", "RcmdrPlugin.steepness", 
"RcmdrPlugin.survival", "RcmdrPlugin.TeachingDemos", "RcmdrPlugin.temis", 
"RcmdrPlugin.UCA", "RColorBrewer", "Rcpp", "RcppArmadillo", "RcppEigen", 
"RCurl", "Rd2roxygen", "RDRToolbox", "readr", "readxl", "registry", 
"reldist", "relimp", "remoji", "reshape", "reshape2", "ResourceSelection", 
"Rfacebook", "rgdal", "rgeos", "rgl", "RGoogleAnalytics", "RgoogleMaps", 
"Rgraphviz", "RGtk2", "RGtk2Extras", "RImageJROI", "RItools", 
"riverplot", "rjags", "rJava", "rjson", "RJSONIO", "rMaps", "rmarkdown", 
"rmdformats", "rmeta", "Rmpfr", "RMySQL", "RnavGraphImageData", 
"rngtools", "ROAuth", "ROCR", "RODBC", "Rook", "roxygen2", "rpart.plot", 
"rpivotTable", "RPostgreSQL", "rscproxy", "rsm", "RSQLite", "rstudio", 
"rstudioapi", "RSvgDevice", "RSVGTipsDevice", "rticles", "rtiff", 
"Rttf2pt1", "runjags", "rversions", "rvest", "rworldmap", "RXKCD", 
"sampling", "sandwich", "scagnostics", "scales", "scatterplot3d", 
"SCMA", "SCRT", "SCVA", "SearchTrees", "seeg", "selectr", "sem", 
"SemiPar", "sendmailR", "sendplot", "sfsmisc", "sgeostat", "shiny", 
"shinyjs", "shinyRGL", "showtext", "showtextdb", "slam", "SLC", 
"sna", "SnowballC", "sos", "sp", "spam", "SparseM", "spatstat", 
"spdep", "startupmsg", "steepness", "stringi", "stringr", "survey", 
"svd", "svglite", "svGUI", "svgViewR", "SweaveListingUtils", 
"sysfonts", "tableone", "tables", "tcltk2", "TeachingDemos", 
"tensor", "testthat", "TH.data", "tibble", "tidyr", "tiff", "tikzDevice", 
"timeDate", "tkrplot", "tm", "tm.plugin.alceste", "tm.plugin.europresse", 
"tm.plugin.factiva", "tm.plugin.lexisnexis", "tourr", "tree", 
"tseries", "TSP", "tufte", "twitteR", "ucminf", "USAboundaries", 
"UScensus2010", "V8", "vcd", "vdmR", "viridis", "viridisLite", 
"visNetwork", "WDI", "wesanderson", "whisker", "withr", "wordcloud", 
"wq", "xkcd", "XLConnect", "XLConnectJars", "xlsx", "xlsxjars", 
"XML", "xml2", "xtable", "xts", "YaleToolkit", "yaml", "zoo")

```


```{r}
install.packages(intersect(max,mozart),lib=.Library)
```

```{r}
library(devtools)
install_github("rstudio/tufte")
install_github("rstudio/tufte-css")
install_github("hadley/productplots")
```

```{r}
library(devtools)
install_github("jverzani/gWidgets2")
install_github("rstudio/gWidgets2RGtk2")
install_github("rstudio/gWidgets2tcltk")
install_github("rstudio/leaflet")
install_github("hadley/densityvis")
install_github("wesm/feather")
```

```{r}
install.packages("addinslist")
```

From GitHub ‘densityvis’, ‘feather’, ‘gWidgets2RGtk2’, ‘gWidgets2tcltk’, ‘productplots’

packages ‘cranvas’, ‘RcmdrPlugin.StatisticalURV’, ‘rstudio’ are not available (for R version 3.3.0)
